model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "inpaint"
    cond_stage_key: "image"
    image_size: 64
    channels: 9
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    u_cond_percent: 0.0 # change to 0.2 for full training!!!!
    scale_factor: 0.18215
    use_ema: False
    learn_logvar: True # try to learn logvar
    
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-5 ]
        f_max: [ 1. ]
        f_min: [ 1. ]
    
    unet_config:
      target: Fantasy-Studio/Paint-by-Example

    use_lora: false
    lora_config:
      rank: 4
      alpha: 8
      dropout: 0.1
      target_modules: null

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      other_params:
        clip_weight: 1.0
        ID_weight: 10.0
        arcface_path: "Other_dependencies/arcface/model_ir_se50.pth"
        concat_feat: False
        land_mark_id_seperate_layers: False
        multi_scale_ID: False # True was used for the previous training there is an issue
        sep_head_att: False
        num_src_images: 2 # same as in config
        Additional_config:
          Reconstruct_initial: True # enables reconstruction and id loss, False is UNSUPPORTED for 9 channel diffusison
          Target_CLIP_feat: False
          Source_CLIP_feat: False
          Multiple_ID_losses: True
          Reconstruct_DDIM_steps: 4
          ID_loss_weight: 0.3
          LPIPS_loss_weight: 0.1
          Landmark_loss_weight: 0.0
        
      

data:
  target: main_swap.DataModuleFromConfig
  params:
      batch_size: 3
      wrap: False
      train:
          target: ldm.data.our_dataset.WildFacesDataset
          params:
              state: train
              dataset_dir: /home/aalanov/Bobkov_Denis/datasets/my_original/final
              json_path: data/filtered_ids3.json
              arbitrary_mask_percent: 0.5
              image_size: 512
              data_seed: 2
              n_src_imgs: 1
              fraction: 0.0001

      validation:
          target: ldm.data.our_dataset.WildFacesDataset
          params:
              state: validation
              dataset_dir: /home/aalanov/Bobkov_Denis/datasets/my_original/final
              json_path: data/filtered_ids3.json
              arbitrary_mask_percent: 0.5
              image_size: 512
              data_seed: 2
              n_src_imgs: 1
              fraction: 0.0001
      test:
          target: ldm.data.our_dataset.WildFacesDataset
          params:
              state: test
              dataset_dir: /home/aalanov/Bobkov_Denis/datasets/my_original/final
              json_path: data/filtered_ids3.json
              arbitrary_mask_percent: 0.5
              image_size: 512
              data_seed: 2
              n_src_imgs: 1
              fraction: 0.0001


# lightning:
#   trainer:
#     max_epochs: 40
#     num_nodes: 1
#     accelerator: 'gpu'
#     gpus: "0,1,2,3,4,5,6,7"
# 1:skin, 2:nose, 3:eye_g, 4:l_eye, 5:r_eye, 6:l_brow, 7:r_brow, 8:l_ear, 9:r_ear, 
# 10:mouth, 11:u_lip, 12:l_lip, 13:hair, 14:hat, 15:ear_r, 16:neck_l, 17:neck, 18:cloth

lightning:
  trainer:
    max_epochs: 50
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "0"